//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAccount
    {
        public decimal Account_No { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public string PhoneNomber { get; set; }
        public string Address { get; set; }
        public byte[] Picture { get; set; }
        public string Gender { get; set; }
        public string Maritial_status { get; set; }
        public string Mother_Name { get; set; }
        public string Father_Name { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Date { get; set; }
    }
}
